// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SaturdayPulse.Data;

#nullable disable

namespace SaturdayPulse.Api.Migrations
{
    [DbContext(typeof(NCAAContext))]
    [Migration("20260527233050_AddPortalMetrics")]
    partial class AddPortalMetrics
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.16");

            modelBuilder.Entity("SaturdayPulse.Models.AvgScoreDelta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Id");

                    b.Property<decimal>("AverageScoreDelta")
                        .HasColumnType("decimal(6,2)")
                        .HasColumnName("AverageScoreDelta");

                    b.Property<int?>("SampleSize")
                        .HasColumnType("INTEGER")
                        .HasColumnName("SampleSize");

                    b.Property<decimal>("StDevP")
                        .HasColumnType("decimal(10,8)")
                        .HasColumnName("StDevP");

                    b.Property<decimal>("Team1WinPct")
                        .HasColumnType("decimal(3,2)")
                        .HasColumnName("Team1WinPct");

                    b.Property<decimal>("Team2WinPct")
                        .HasColumnType("decimal(3,2)")
                        .HasColumnName("Team2WinPct");

                    b.HasKey("Id");

                    b.ToTable("AvgScoreDeltas");
                });

            modelBuilder.Entity("SaturdayPulse.Models.AvgScoreDifferential", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AverageMargin")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("AverageTotalPoints")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastUpdatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("SampleSize")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("StdDevMargin")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("StrengthDifferential")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("StrengthDifferential")
                        .IsUnique();

                    b.ToTable("AvgScoreDifferentials");
                });

            modelBuilder.Entity("SaturdayPulse.Models.Conference", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Abbreviation")
                        .HasColumnType("TEXT");

                    b.Property<string>("Classification")
                        .HasColumnType("TEXT");

                    b.Property<int>("ConferenceId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ShortName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ConferenceId")
                        .IsUnique()
                        .HasDatabaseName("UQ_Conferences_ConferenceId");

                    b.ToTable("Conferences");
                });

            modelBuilder.Entity("SaturdayPulse.Models.Games", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Attendance")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AwayId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AwayName")
                        .HasColumnType("TEXT");

                    b.Property<int?>("AwayPoints")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ConferenceGame")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GameDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("GameDay")
                        .HasColumnType("TEXT");

                    b.Property<int>("GameId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("HomeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HomeName")
                        .HasColumnType("TEXT");

                    b.Property<int?>("HomePoints")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("NeutralSite")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SeasonType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Venue")
                        .HasColumnType("TEXT");

                    b.Property<int>("Week")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GameId")
                        .IsUnique()
                        .HasDatabaseName("UQ_Games_GameId");

                    b.HasIndex("Year", "Week")
                        .HasDatabaseName("IX_Games_Year_Week");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("SaturdayPulse.Models.Lines", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AwayMoneyline")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FormattedSpread")
                        .HasColumnType("TEXT");

                    b.Property<int>("GameId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("HomeMoneyline")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("OverUnder")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("OverUnderOpen")
                        .HasColumnType("TEXT");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Spread")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("SpreadOpen")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Lines");
                });

            modelBuilder.Entity("SaturdayPulse.Models.MatchupHistory", b =>
                {
                    b.Property<int>("Team1Id")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Team1Id")
                        .HasColumnOrder(0);

                    b.Property<int>("Team2Id")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Team2Id")
                        .HasColumnOrder(1);

                    b.Property<decimal>("AvgMargin")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("AvgMargin");

                    b.Property<int>("FirstPlayed")
                        .HasColumnType("INTEGER")
                        .HasColumnName("FirstPlayed");

                    b.Property<int>("GamesPlayed")
                        .HasColumnType("INTEGER")
                        .HasColumnName("GamesPlayed");

                    b.Property<int>("LastPlayed")
                        .HasColumnType("INTEGER")
                        .HasColumnName("LastPlayed");

                    b.Property<string>("RivalryName")
                        .HasColumnType("varchar(100)")
                        .HasColumnName("RivalryName");

                    b.Property<string>("RivalryTier")
                        .HasColumnType("varchar(20)")
                        .HasColumnName("RivalryTier");

                    b.Property<decimal>("StDevMargin")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("StDevMargin");

                    b.Property<decimal>("UpsetRate")
                        .HasColumnType("decimal(4,3)")
                        .HasColumnName("UpsetRate");

                    b.HasKey("Team1Id", "Team2Id");

                    b.ToTable("MatchupHistory");
                });

            modelBuilder.Entity("SaturdayPulse.Models.PortalEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Id");

                    b.Property<string>("Destination")
                        .HasColumnType("TEXT")
                        .HasColumnName("Destination");

                    b.Property<string>("Eligibility")
                        .HasColumnType("TEXT")
                        .HasColumnName("Eligibility");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT")
                        .HasColumnName("FirstName");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT")
                        .HasColumnName("LastName");

                    b.Property<string>("Origin")
                        .HasColumnType("TEXT")
                        .HasColumnName("Origin");

                    b.Property<string>("Position")
                        .HasColumnType("TEXT")
                        .HasColumnName("Position");

                    b.Property<double?>("Rating")
                        .HasColumnType("REAL")
                        .HasColumnName("Rating");

                    b.Property<int>("Season")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Season");

                    b.Property<int?>("Stars")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Stars");

                    b.Property<string>("TransferDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("TransferDate");

                    b.HasKey("Id");

                    b.HasIndex("Destination");

                    b.HasIndex("Origin");

                    b.HasIndex("Season");

                    b.ToTable("PortalEntries");
                });

            modelBuilder.Entity("SaturdayPulse.Models.Projection", b =>
                {
                    b.Property<int>("ProjectionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AwayTeamId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GameId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HomeTeamId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("HomeWinProbability")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PredictedSpread")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PredictedTotal")
                        .HasColumnType("TEXT");

                    b.Property<int>("Week")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("ProjectionId");

                    b.ToTable("Projections");
                });

            modelBuilder.Entity("SaturdayPulse.Models.TeamRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Id");

                    b.Property<decimal>("AvgPointsAllowed")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("AvgPointsAllowed");

                    b.Property<decimal>("AvgPointsScored")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("AvgPointsScored");

                    b.Property<decimal?>("BaseSOS")
                        .HasColumnType("decimal(10,3)")
                        .HasColumnName("BaseSOS");

                    b.Property<decimal?>("CombinedSOS")
                        .HasColumnType("decimal(10,4)")
                        .HasColumnName("CombinedSOS");

                    b.Property<int>("DefensiveRank")
                        .HasColumnType("INTEGER")
                        .HasColumnName("DefensiveRank");

                    b.Property<decimal>("DefensiveZScore")
                        .HasColumnType("decimal(7,4)")
                        .HasColumnName("DefensiveZScore");

                    b.Property<byte>("Losses")
                        .HasColumnType("smallint")
                        .HasColumnName("Losses");

                    b.Property<int>("OffensiveRank")
                        .HasColumnType("INTEGER")
                        .HasColumnName("OffensiveRank");

                    b.Property<decimal>("OffensiveZScore")
                        .HasColumnType("decimal(7,4)")
                        .HasColumnName("OffensiveZScore");

                    b.Property<decimal?>("PedigreeRating")
                        .HasColumnType("decimal(10,4)")
                        .HasColumnName("PedigreeRating");

                    b.Property<int>("PointsAgainst")
                        .HasColumnType("INTEGER")
                        .HasColumnName("PointsAgainst");

                    b.Property<int>("PointsFor")
                        .HasColumnType("INTEGER")
                        .HasColumnName("PointsFor");

                    b.Property<decimal?>("PortalDelta")
                        .HasColumnType("decimal(10,4)")
                        .HasColumnName("PortalDelta");

                    b.Property<decimal?>("PowerRating")
                        .HasColumnType("decimal(10,4)")
                        .HasColumnName("PowerRating");

                    b.Property<decimal?>("Ranking")
                        .HasColumnType("decimal(10,4)")
                        .HasColumnName("Ranking");

                    b.Property<decimal?>("RosterStrength")
                        .HasColumnType("decimal(10,4)")
                        .HasColumnName("RosterStrength");

                    b.Property<decimal?>("SeedRating")
                        .HasColumnType("decimal(10,4)")
                        .HasColumnName("SeedRating");

                    b.Property<decimal?>("SubSOS")
                        .HasColumnType("decimal(10,3)")
                        .HasColumnName("SubSOS");

                    b.Property<int>("TeamID")
                        .HasColumnType("INTEGER")
                        .HasColumnName("TeamID");

                    b.Property<decimal?>("TrendRating")
                        .HasColumnType("decimal(10,4)")
                        .HasColumnName("TrendRating");

                    b.Property<byte>("Wins")
                        .HasColumnType("smallint")
                        .HasColumnName("Wins");

                    b.Property<short>("Year")
                        .HasColumnType("smallint")
                        .HasColumnName("Year");

                    b.HasKey("Id");

                    b.HasIndex("TeamID");

                    b.ToTable("TeamRecords");
                });

            modelBuilder.Entity("SaturdayPulse.Models.Teams", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Abbreviation")
                        .HasColumnType("TEXT");

                    b.Property<string>("Alias")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ConferenceID")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ConferenceId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Division")
                        .HasColumnType("TEXT");

                    b.Property<string>("Mascot")
                        .HasColumnType("TEXT");

                    b.Property<string>("ShortName")
                        .HasColumnType("TEXT");

                    b.Property<int>("TeamId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TeamName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ConferenceID");

                    b.HasIndex("TeamId")
                        .IsUnique()
                        .HasDatabaseName("UQ_Teams_TeamId");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("SaturdayPulse.Models.TeamsConferenceHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ConferenceId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("EndYear")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StartYear")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TeamId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TeamId", "StartYear")
                        .IsUnique()
                        .HasDatabaseName("UQ_TeamsConferenceHistory_TeamId_StartYear");

                    b.ToTable("TeamsConferenceHistory");
                });

            modelBuilder.Entity("SaturdayPulse.Models.WeeklyRanking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Id");

                    b.Property<decimal>("AvgPointsAllowed")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("AvgPointsAllowed");

                    b.Property<decimal>("AvgPointsScored")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("AvgPointsScored");

                    b.Property<decimal?>("BaseSOS")
                        .HasColumnType("decimal(10,3)")
                        .HasColumnName("BaseSOS");

                    b.Property<decimal?>("CombinedSOS")
                        .HasColumnType("decimal(10,4)")
                        .HasColumnName("CombinedSOS");

                    b.Property<int>("DefensiveRank")
                        .HasColumnType("INTEGER")
                        .HasColumnName("DefensiveRank");

                    b.Property<decimal>("DefensiveZScore")
                        .HasColumnType("decimal(7,4)")
                        .HasColumnName("DefensiveZScore");

                    b.Property<byte>("Losses")
                        .HasColumnType("smallint")
                        .HasColumnName("Losses");

                    b.Property<int>("OffensiveRank")
                        .HasColumnType("INTEGER")
                        .HasColumnName("OffensiveRank");

                    b.Property<decimal>("OffensiveZScore")
                        .HasColumnType("decimal(7,4)")
                        .HasColumnName("OffensiveZScore");

                    b.Property<int>("OverallRank")
                        .HasColumnType("INTEGER")
                        .HasColumnName("OverallRank");

                    b.Property<int>("PointsAgainst")
                        .HasColumnType("INTEGER")
                        .HasColumnName("PointsAgainst");

                    b.Property<int>("PointsFor")
                        .HasColumnType("INTEGER")
                        .HasColumnName("PointsFor");

                    b.Property<decimal?>("PowerRating")
                        .HasColumnType("decimal(10,4)")
                        .HasColumnName("PowerRating");

                    b.Property<decimal?>("Ranking")
                        .HasColumnType("decimal(10,4)")
                        .HasColumnName("Ranking");

                    b.Property<decimal?>("RosterStrength")
                        .HasColumnType("decimal(10,4)")
                        .HasColumnName("RosterStrength");

                    b.Property<decimal?>("SubSOS")
                        .HasColumnType("decimal(10,3)")
                        .HasColumnName("SubSOS");

                    b.Property<int>("TeamID")
                        .HasColumnType("INTEGER")
                        .HasColumnName("TeamID");

                    b.Property<int>("TierRank")
                        .HasColumnType("INTEGER")
                        .HasColumnName("TierRank");

                    b.Property<byte>("Week")
                        .HasColumnType("smallint")
                        .HasColumnName("Week");

                    b.Property<byte>("Wins")
                        .HasColumnType("smallint")
                        .HasColumnName("Wins");

                    b.Property<short>("Year")
                        .HasColumnType("smallint")
                        .HasColumnName("Year");

                    b.HasKey("Id");

                    b.HasIndex("TeamID");

                    b.ToTable("WeeklyRankings");
                });

            modelBuilder.Entity("SaturdayPulse.Models.TeamRecord", b =>
                {
                    b.HasOne("SaturdayPulse.Models.Teams", "Teams")
                        .WithMany()
                        .HasForeignKey("TeamID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Teams");
                });

            modelBuilder.Entity("SaturdayPulse.Models.Teams", b =>
                {
                    b.HasOne("SaturdayPulse.Models.Conference", "Conference")
                        .WithMany()
                        .HasForeignKey("ConferenceID");

                    b.Navigation("Conference");
                });

            modelBuilder.Entity("SaturdayPulse.Models.WeeklyRanking", b =>
                {
                    b.HasOne("SaturdayPulse.Models.Teams", "Team")
                        .WithMany()
                        .HasForeignKey("TeamID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });
#pragma warning restore 612, 618
        }
    }
}
