// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SaturdayPulse.Data;

#nullable disable

namespace SaturdayPulse.Migrations
{
    [DbContext(typeof(NCAAContext))]
    partial class NCAAContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SaturdayPulse.Models.AvgScoreDelta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AverageScoreDelta")
                        .HasColumnType("decimal(6,2)")
                        .HasColumnName("AverageScoreDelta");

                    b.Property<int?>("SampleSize")
                        .HasColumnType("int")
                        .HasColumnName("SampleSize");

                    b.Property<decimal>("StDevP")
                        .HasColumnType("decimal(10,8)")
                        .HasColumnName("StDevP");

                    b.Property<decimal>("Team1WinPct")
                        .HasColumnType("decimal(3,2)")
                        .HasColumnName("Team1WinPct");

                    b.Property<decimal>("Team2WinPct")
                        .HasColumnType("decimal(3,2)")
                        .HasColumnName("Team2WinPct");

                    b.HasKey("Id");

                    b.ToTable("AvgScoreDeltas");
                });

            modelBuilder.Entity("SaturdayPulse.Models.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("GameDate")
                        .HasColumnType("varchar(20)")
                        .HasColumnName("GameDate");

                    b.Property<string>("GameDay")
                        .HasColumnType("varchar(3)")
                        .HasColumnName("GameDay");

                    b.Property<int>("LPoints")
                        .HasColumnType("int")
                        .HasColumnName("LPoints");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)")
                        .HasColumnName("Location");

                    b.Property<int>("LoserId")
                        .HasColumnType("int")
                        .HasColumnName("LoserId");

                    b.Property<string>("LoserName")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("LoserName");

                    b.Property<int>("WPoints")
                        .HasColumnType("int")
                        .HasColumnName("WPoints");

                    b.Property<int>("Week")
                        .HasColumnType("int")
                        .HasColumnName("Week");

                    b.Property<int>("WinnerId")
                        .HasColumnType("int")
                        .HasColumnName("WinnerId");

                    b.Property<string>("WinnerName")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("WinnerName");

                    b.Property<int>("Year")
                        .HasColumnType("int")
                        .HasColumnName("Year");

                    b.HasKey("Id");

                    b.ToTable("Game");
                });

            modelBuilder.Entity("SaturdayPulse.Models.MatchupHistory", b =>
                {
                    b.Property<int>("Team1Id")
                        .HasColumnType("int")
                        .HasColumnName("Team1Id")
                        .HasColumnOrder(0);

                    b.Property<int>("Team2Id")
                        .HasColumnType("int")
                        .HasColumnName("Team2Id")
                        .HasColumnOrder(1);

                    b.Property<decimal>("AvgMargin")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("AvgMargin");

                    b.Property<int>("FirstPlayed")
                        .HasColumnType("int")
                        .HasColumnName("FirstPlayed");

                    b.Property<int>("GamesPlayed")
                        .HasColumnType("int")
                        .HasColumnName("GamesPlayed");

                    b.Property<int>("LastPlayed")
                        .HasColumnType("int")
                        .HasColumnName("LastPlayed");

                    b.Property<string>("RivalryName")
                        .HasColumnType("varchar(100)")
                        .HasColumnName("RivalryName");

                    b.Property<string>("RivalryTier")
                        .HasColumnType("varchar(20)")
                        .HasColumnName("RivalryTier");

                    b.Property<decimal>("StDevMargin")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("StDevMargin");

                    b.Property<decimal>("UpsetRate")
                        .HasColumnType("decimal(4,3)")
                        .HasColumnName("UpsetRate");

                    b.HasKey("Team1Id", "Team2Id");

                    b.ToTable("MatchupHistory");
                });

            modelBuilder.Entity("SaturdayPulse.Models.Team", b =>
                {
                    b.Property<int>("TeamID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("TeamID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TeamID"));

                    b.Property<string>("Alias")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Alias");

                    b.Property<string>("Conference")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Conference");

                    b.Property<string>("ConferenceAbbr")
                        .HasColumnType("varchar(10)")
                        .HasColumnName("ConferenceAbbr");

                    b.Property<string>("Division")
                        .HasColumnType("varchar(20)")
                        .HasColumnName("Division");

                    b.Property<string>("ShortName")
                        .HasColumnType("varchar(20)")
                        .HasColumnName("ShortName");

                    b.Property<string>("TeamName")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("TeamName");

                    b.HasKey("TeamID");

                    b.ToTable("Team");
                });

            modelBuilder.Entity("SaturdayPulse.Models.TeamRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AvgPointsAllowed")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("AvgPointsAllowed");

                    b.Property<decimal>("AvgPointsScored")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("AvgPointsScored");

                    b.Property<decimal?>("BaseSOS")
                        .HasColumnType("decimal(10,3)")
                        .HasColumnName("BaseSOS");

                    b.Property<decimal?>("CombinedSOS")
                        .HasColumnType("decimal(10,4)")
                        .HasColumnName("CombinedSOS");

                    b.Property<int>("DefensiveRank")
                        .HasColumnType("int")
                        .HasColumnName("DefensiveRank");

                    b.Property<decimal>("DefensiveZScore")
                        .HasColumnType("decimal(7,4)")
                        .HasColumnName("DefensiveZScore");

                    b.Property<byte>("Losses")
                        .HasColumnType("tinyint")
                        .HasColumnName("Losses");

                    b.Property<int>("OffensiveRank")
                        .HasColumnType("int")
                        .HasColumnName("OffensiveRank");

                    b.Property<decimal>("OffensiveZScore")
                        .HasColumnType("decimal(7,4)")
                        .HasColumnName("OffensiveZScore");

                    b.Property<int>("PointsAgainst")
                        .HasColumnType("int")
                        .HasColumnName("PointsAgainst");

                    b.Property<int>("PointsFor")
                        .HasColumnType("int")
                        .HasColumnName("PointsFor");

                    b.Property<decimal?>("PowerRating")
                        .HasColumnType("decimal(10,4)")
                        .HasColumnName("PowerRating");

                    b.Property<decimal?>("Ranking")
                        .HasColumnType("decimal(10,4)")
                        .HasColumnName("Ranking");

                    b.Property<decimal?>("SubSOS")
                        .HasColumnType("decimal(10,3)")
                        .HasColumnName("SubSOS");

                    b.Property<int>("TeamID")
                        .HasColumnType("int")
                        .HasColumnName("TeamID");

                    b.Property<byte>("Wins")
                        .HasColumnType("tinyint")
                        .HasColumnName("Wins");

                    b.Property<short>("Year")
                        .HasColumnType("smallint")
                        .HasColumnName("Year");

                    b.HasKey("Id");

                    b.HasIndex("TeamID");

                    b.ToTable("TeamRecords");
                });

            modelBuilder.Entity("SaturdayPulse.Models.WeeklyRanking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AvgPointsAllowed")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("AvgPointsAllowed");

                    b.Property<decimal>("AvgPointsScored")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("AvgPointsScored");

                    b.Property<decimal?>("BaseSOS")
                        .HasColumnType("decimal(10,3)")
                        .HasColumnName("BaseSOS");

                    b.Property<decimal?>("CombinedSOS")
                        .HasColumnType("decimal(10,4)")
                        .HasColumnName("CombinedSOS");

                    b.Property<int>("DefensiveRank")
                        .HasColumnType("int")
                        .HasColumnName("DefensiveRank");

                    b.Property<decimal>("DefensiveZScore")
                        .HasColumnType("decimal(7,4)")
                        .HasColumnName("DefensiveZScore");

                    b.Property<byte>("Losses")
                        .HasColumnType("tinyint")
                        .HasColumnName("Losses");

                    b.Property<int>("OffensiveRank")
                        .HasColumnType("int")
                        .HasColumnName("OffensiveRank");

                    b.Property<decimal>("OffensiveZScore")
                        .HasColumnType("decimal(7,4)")
                        .HasColumnName("OffensiveZScore");

                    b.Property<int>("OverallRank")
                        .HasColumnType("int")
                        .HasColumnName("OverallRank");

                    b.Property<int>("PointsAgainst")
                        .HasColumnType("int")
                        .HasColumnName("PointsAgainst");

                    b.Property<int>("PointsFor")
                        .HasColumnType("int")
                        .HasColumnName("PointsFor");

                    b.Property<decimal?>("PowerRating")
                        .HasColumnType("decimal(10,4)")
                        .HasColumnName("PowerRating");

                    b.Property<decimal?>("Ranking")
                        .HasColumnType("decimal(10,4)")
                        .HasColumnName("Ranking");

                    b.Property<decimal?>("SubSOS")
                        .HasColumnType("decimal(10,3)")
                        .HasColumnName("SubSOS");

                    b.Property<int>("TeamID")
                        .HasColumnType("int")
                        .HasColumnName("TeamID");

                    b.Property<int>("TierRank")
                        .HasColumnType("int")
                        .HasColumnName("TierRank");

                    b.Property<byte>("Week")
                        .HasColumnType("tinyint")
                        .HasColumnName("Week");

                    b.Property<byte>("Wins")
                        .HasColumnType("tinyint")
                        .HasColumnName("Wins");

                    b.Property<short>("Year")
                        .HasColumnType("smallint")
                        .HasColumnName("Year");

                    b.HasKey("Id");

                    b.HasIndex("TeamID", "Year", "Week")
                        .IsUnique();

                    b.ToTable("WeeklyRankings");
                });

            modelBuilder.Entity("SaturdayPulse.Models.TeamRecord", b =>
                {
                    b.HasOne("SaturdayPulse.Models.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("SaturdayPulse.Models.WeeklyRanking", b =>
                {
                    b.HasOne("SaturdayPulse.Models.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });
#pragma warning restore 612, 618
        }
    }
}
